return {
  "/gamemode [owner] creative",
  "Hi friend [user]!",
  "ああ、今日は最悪な日になりそうだ... ちょっと体調が優れないから、[user] 頑張ってね :) !",
  "Ā, kyō wa saiakuna hi ni nari-sōda... Chotto taichō ga sugurenaikara,[user] ganbattene: )!",
  "아, 오늘은 나쁜 하루가 될 것 같네요... 몸이 좀 안 좋아서요. 행운을 빌어요 [user] :) !",
  "a, oneul-eun nappeun haluga doel geos gatneyo... mom-i jom an joh-aseoyo. haeng-un-eul bil-eoyo [user] :) !",
  "오, 당신은 강력한 상대처럼 보이네요. 하지만 당신 [user] 은 아직 어리고, 경험도 부족하고, 너무 소심해서 저를 이길 수 없어요!",
  "o, dangsin-eun ganglyeoghan sangdaecheoleom boineyo. hajiman dangsin [user] eun ajig eoligo, gyeongheomdo bujoghago, neomu sosimhaeseo jeoleul igil su eobs-eoyo!",
  "ERROR... [owner]!",
  "i [user] leul beon-yeoghaneun de sigan-eul nangbihaji maseyo =))"
  context = {"%[owner%]", "%[user%]"}
}
